### ISSUE TITLE
I have problem 

### ISSUE THREAD

**Issue by kalina-p** [reptilex/tesla-style-solar-power-card#101]
That is my configuration:

type: custom:tesla-style-solar-power-card
generation_to_grid_entity: sensor.power_photovoltaics_fronius_power_flow

when I add configurations I can see the icons correctly
Please look on that:
![1](https://user-images.githubusercontent.com/78249685/150673310-cea088ea-ac04-4749-8a96-286c9f2d6f8f.jpg)

but when I save configuration icons is very small and I cannot see what it display

![2](https://user-images.githubusercontent.com/78249685/150673328-c19eab00-4752-4d72-9983-b0179b6f31b0.jpg)

Could someone help me with that ?

Best Regards

**Comment by JacoboSanchez** [comment]
Don't know the cause but if you close the dashboard edition and make any change that leads to redraw the diagram (for example changing the size of the browser's window) It should repaint itself with the correct size

**Comment by reptilex** [comment]
The reason is because HA does not give you a value for the size of the card from the start and since my visualization is an scg pixel graph that depends on the size the calculation does not work. As soon as you reload HA gives a size and the graphs look good again :( 
I have a plan to replace the svg pixel graphs but it seems this will take a year because I have no time.
