### ISSUE TITLE
Recommended setup for house reporting

### ISSUE THREAD

**Issue by hofvanta** [reptilex/tesla-style-solar-power-card#105]
Dear all,

I use the card already some time with a lot of happiness. In most setups the house is acting as a power hub, that means that not only EV charger , but also heatpump and so on are connected to. In this way the house consumption is not visible any more (power consolidation). Is there an option to breaking the house consumption entity/icon to show and extra entity within the house icon of calculated house consumption, instead of total? Like <house>/<total> and make the icon smaller to see not the total but also the house only consumption?

**Comment by Avatar1976** [comment]
> Dear all,
> 
> I use the card already some time with a lot of happiness. In most setups the house is acting as a power hub, that means that not only EV charger , but also heatpump and so on are connected to. In this way the house consumption is not visible any more (power consolidation). Is there an option to breaking the house consumption entity/icon to show and extra entity within the house icon of calculated house consumption, instead of total? Like / and make the icon smaller to see not the total but also the house only consumption?

Do you mean outside the two extra break out icons @reptilex has already provided? Car and Heatpump / AC?

**Comment by hofvanta** [comment]
Yes thats correct. House icon is actual an hub and not able to differentiate the actual use of the house only 
In each icon most people I think show the real Watt counter and extra identity the total kWh during the day and then there is not space anymore to show other entities. Already tried to remove the icon and show a third entry in the house bubble, but was not succesful. And extra entry in the bubble or an extra one should be nice.

**Comment by reptilex** [comment]
I understand what you mean, but changing this would mean that the flow lines would need to go from each consumption bubble to solar, battery and grid and that is way too complicated. So either you use the house as a hub or your sum of usage will never be correct (aka if you use the house with a template that substracts the other usages. What you can do is add a template for the top value of the house icon, that shows you the "appliance or house consumption without the extra appliances on the two extra bubbles. But I have a few separate cards for that, because I'm only interested in the daily not the current usage for the house.

**Comment by hofvanta** [comment]
Clear/ Thanks to investigate. Is it possible to use a text string with a combination of the current values? Or use an extra entity instead of the house icon?

**Comment by reptilex** [comment]
I have added the possibility to subtract the value of the appliances from the house bubble. The flows though will stay bound to the house, since most users have entities bound to their solar converters and because changing the flow lines is a real struggle. Check the documentation on the latest release.
Also you can use an extra entity to show on the top part of any bubble.
