### ISSUE TITLE
Probably user error rather than an actual issue...

### ISSUE THREAD

**Issue by C00K50N** [reptilex/tesla-style-solar-power-card#133]
...but can anyone help me?  I love this card but can't seem to get it set up right.  Below are a couple screenshots of where I'm up to.  Grid use seems to be correct, and house load isn't far off, but when we're generating power the battery and generation figures go way off.  I suspect there's some addition going on so I can't have set it up properly, but I can't work out where I've gone wrong.

The gauges below the flow card can be taken as accurate...

![image](https://user-images.githubusercontent.com/102669305/198972019-70c55571-ba28-431e-923c-ace8cbb90629.png) 
![image](https://user-images.githubusercontent.com/102669305/198972088-ec831ed5-e389-4b52-8ce4-3d6ad55f7c04.png)

Here's my code at the moment:
![image](https://user-images.githubusercontent.com/102669305/198972923-cd156b83-22cd-46ae-b0ae-727f7bde23b3.png)

**Comment by reptilex** [comment]
The issue is your sensors are not showing the actual feeds the card needs. For example the sensor.pv_total_power is probably the overall consumption and not only the power being sent to house from pv. So you have to create template sensors to accomodate the flows. I'm not 100% sure so check it out but for example:

generation_to_house need to be a new template sensor with pv_total_power - feed_in_power - battery_charge

But there is something strange about you battery charge/discharge sensors, at least charge seems to have positive values when you are not charging.

The card needs you to separate each flow from each other. So charge is only charge, discharge is only discharge pv_to_house is only that.
