### ISSUE TITLE
Card not always drawn properly

### ISSUE THREAD

**Issue by tacognito** [reptilex/tesla-style-solar-power-card#16]
Hi reptilex,

First of all, aweseme card! It looks great. Just got a problem with how it's drawn when in a stack (vertical, horizontal or grid). It seems to compact the drawing space of the card resulting in a bad placement of the cards element. 

See screenshot attached.
![Screenshot 2020-11-21 at 16 47 26](https://user-images.githubusercontent.com/65339720/99881366-aa6ce580-2c19-11eb-90c0-a963c89120f2.png)

The above is a plain manual card, below a manual card in a vertical stack.

Maybe related: when adding the vertical stack card in the screenshot, the normal card becomes a very small blank card. When I edit that top card and remove the trailing blank line in the code editor, it reverts back the normal drawing... Very peculiar.

Thanks in advance for the help!

Cheers

**Comment by reptilex** [comment]
Ok. I hopw I will get to this in the upcoming days, but my guess is that vertical stack will just not be supported, the problem lies in the svg calculation and how I have figured out to do that. Unless you can help me I'll probably will do a not fix of this. But first I'll check.

**Comment by reptilex** [comment]
Ok I know why this is happening and although I could hack it for it to work, I'm looking for a generic solution. My problem is currently that in home assistant they are using custom dom tags, which are pretty cool, but they do not allow to search for dom elements in all the dom tree, and since stacks are custom for each ha installation I cannot hardcode this. I have asked for help to the frontend guys, maybe I get a non hacky solution soon.

**Comment by reptilex** [comment]
The answer to my hack was ... let's just say me not being such a noob. It's solved ...

**Comment by tacognito** [comment]
Thanks reptilex! Really appreciate it!!
