### ISSUE TITLE
Clicking bubbles in Version 1.1.6

### ISSUE THREAD

**Issue by PierreScerri** [reptilex/tesla-style-solar-power-card#45]
First of all thank you for taking the time to address all the issues that come up.

I have v1.1.6 installed and this is my config:

```
type: 'custom:tesla-style-solar-power-card'
hide_inactive_lines: 1
show_w_not_kw: 1

## Bubbles
grid_consumption_entity: sensor.sdm230power 
         ## this can be + or -.  (Can use sensor.import_power but it makes no difference)
house_consumption_entity: sensor.house_power
generation_yield_entity: sensor.sdm120power

## Flows
grid_to_house_entity: sensor.import_power
generation_to_grid_entity: sensor.export_power
generation_to_house_entity: sensor.solar_use
```
The bubbles are not responding to clicks.  Tried browsers and HA app an iPhone and iMac.  The only reaction to a click on a bubble is a blue rectangle around the card:

![Screenshot 2021-03-29 at 13 19 33](https://user-images.githubusercontent.com/34303331/112829459-73a84f80-9091-11eb-9bfc-e42bb9aa5c32.png)

Also the Grid bubble displays a '-' when solar is exporting to the grid.  Is this intentional.  Not complaining, just to know.

**Comment by reptilex** [comment]
Your welcome. Yes the - is intentional. 
The bubbles don't work when clicked because silly me decided to change the names of the entities, they are now:
* grid_entity
* house_entity
* generation_entity
* battery_entity (in case you add it)

About the +/- I wanted to make it clear when something is getting or giving energy. I guess it's a bit strange since battery is minus on giving and grid is minus on receiving, but from a context point of view I think it makes sense. Battery is being charged is + and battery being discharged is -. From a grid perspective normal is giving energy and atipical would be to get energy. But yeah, don't know if it should stay that way.

If that does the trick as I expect please close the issue ;)

**Comment by PierreScerri** [comment]
Entities adjusted and clickable.
The '-' makes sense to me too.
Thanks for the explanation.

Excellent work.
