### ISSUE TITLE
Tesla powerwall integration card config

### ISSUE THREAD

**Issue by haberda** [reptilex/tesla-style-solar-power-card#46]
Hi,

I have the Tesla PW Integration setup with solar panels and battery backup. In order to get the card to display properly I had to used the following configuration:

```
type: 'custom:tesla-style-solar-power-card'
house_consumption_entity: sensor.powerwall_load_now
grid_feed_in_entity: sensor.tesla_card_grid_feed_in
grid_consumption_entity: sensor.tesla_card_grid_consumption
grid_to_house_entity: sensor.tesla_card_grid_consumption
battery_consumption_entity: sensor.tesla_card_battery_consumption
solar_consumption_entity: sensor.tesla_card_solar_consumption
solar_yield_entity: sensor.powerwall_solar_now
generation_yield_entity: sensor.powerwall_solar_now
generation_to_grid: sensor.tesla_card_grid_feed_in
generation_to_house_entity: sensor.tesla_card_solar_consumption
generation_to_battery_entity: sensor.tesla_card_battery_charging
battery_to_house_entity: sensor.tesla_card_battery_consumption
battery_charging_entity: sensor.tesla_card_battery_charging
battery_charge_entity: sensor.powerwall_charge
```

The config provided in the README did not populate the battery, solar yield and consumption, or grid consumption. The sensor configs you provided worked well.

Thanks for the hard work!

**Comment by reptilex** [comment]
You are probably using an old version since the stable Release 1.1. You should only need the flows:
generation_to_grid: sensor.tesla_card_grid_feed_in
generation_to_house_entity: sensor.tesla_card_solar_consumption
generation_to_battery_entity: sensor.tesla_card_battery_charging
grid_to_house_entity: sensor.tesla_card_grid_consumption
battery_to_house_entity: sensor.tesla_card_battery_consumption

The optional click entities for the bubbles would be:
generation_entity:sensor.powerwall_solar_now
house_entity:sensor.powerwall_load_now
battery_entity:sensor.powerwall_charge
grid_entity:sensor.tesla_card_grid_consumption

Try that with the latest version, should work. The rest you should not need.

**Comment by haberda** [comment]
According to HACS I am running v1.1.6. Is it possible that it did not update cleanly? I will delete and reinstall to see if that helps.

**Comment by haberda** [comment]
Ok, yeah. I deleted the card from the UI, then removed it from HACS. After I reinstalled your config works. Thanks!
