### ISSUE TITLE
Line EV improvement suggestion

### ISSUE THREAD

**Issue by chrislader** [reptilex/tesla-style-solar-power-card#51]
This card keeps getting better and better, compliments for that!

I noticed the EV line from house not aligning perfectly yet. Could you fix this? or point at the line in the code where this is managed; I could trial-and-error the best alignment.

![image](https://user-images.githubusercontent.com/40333466/113922432-92bc8500-97e7-11eb-9d89-5e2b687e7d2d.png)

**Comment by reptilex** [comment]
You are welcome to try. I have a few times, it is rather hard, due to being probably the wrong way of doing it. My plan to solve it for good is to change my current svg paths to css and stop doing svg animations and exchange them with css ones. That is probably going to be version 2.0. But will take a few months.
If you want to have a go try here:
play around with lines 200 to 260 on the HtmlResizePowerCard.ts file 
https://github.com/reptilex/tesla-style-solar-power-card/blob/master/src/services/HtmlResizeForPowerCard.ts
I could not figure out how to do better resizing with svg's than this. But I know there has to be a much better way.
Ping me if you need some pointers or come up with a better idea ;)

**Comment by vvuk** [comment]
I took a stab at creating this with CSS grid -- you can see the start here https://codepen.io/vvuk/pen/eYvvmxm .  With grid + %-based sizing/alignment, should be able to get everything perfectly aligned at any size (some of the bits in my sample aren't perfect, I eyeballed percentages instead of actually doing the right math :) ).  If I have time I may take a stab at converting the card over, but wanted to leave that link here anyway in case it's useful.

**Comment by pman07** [comment]
Below are some changes I've made, For the vertical lines I changed "t" to "t-this.pxRate" to center the lines related to the solar and battery entities. I also screwed with the Appliance 1 and 2 lines a bit, still not perfect but looks good enough for my devices.

![image](https://user-images.githubusercontent.com/56171396/121716127-46224e00-caa5-11eb-967a-55d3f605ebcc.png)


                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="${"0 0 "+42*this.pxRate+" "+42*this.pxRate}"
                  preserveAspectRatio="xMinYMax slice"
                  style="height:${42*this.pxRate+"px"};width:${42*this.pxRate+"px"}"
                >
                  ${this.htmlWriter.writeCircleAndLine("generation_to_house_entity","M"+(t-this.pxRate)+",0 C"+(t-this.pxRate)+","+(t)+" "+(t-this.pxRate)+","+(t)+" "+2*t+","+(t))}
                  ${this.htmlWriter.writeCircleAndLine("grid_to_house_entity","M0,"+t+" C"+t+","+t+" "+t+","+t+" "+2*t+","+t)}
                  ${this.htmlWriter.writeCircleAndLine("generation_to_grid_entity","M"+(t-this.pxRate)+",0 C"+(t-this.pxRate)+","+(t)+" "+(t-this.pxRate)+","+(t)+" 0,"+(t))}
                  ${this.htmlWriter.writeCircleAndLine("grid_to_battery_entity","M0,"+t+" C"+t+","+t+" "+t+","+t+" "+t+","+2*t)}
                  ${this.htmlWriter.writeCircleAndLine("battery_to_grid_entity","M"+(t-this.pxRate)+","+2*t+" C"+(t-this.pxRate)+","+(t)+" "+(t-this.pxRate)+","+(t)+" 0,"+(t))}
                  ${this.htmlWriter.writeCircleAndLine("generation_to_battery_entity","M"+(t-this.pxRate)+",0 C"+(t-this.pxRate)+",0 "+(t-this.pxRate)+","+2*t+" "+(t-this.pxRate)+","+2*t)}
                  ${this.htmlWriter.writeCircleAndLine("battery_to_house_entity","M"+(t-this.pxRate)+","+2*t+" C"+(t-this.pxRate)+","+(t)+" "+(t-this.pxRate)+","+(t)+" "+2*t+","+(t))}
                </svg>
              </div>

              ${this.writeHouseIconBubble()} ${this.writeApplianceIconBubble(1)}
              ${this.htmlWriter.writeAppliancePowerLineAndCircle(1,"M" + 1.7*this.pxRate+ ","+18*this.pxRate+" C" + 1.7*this.pxRate+ ","+18*this.pxRate+" " + 1.7*this.pxRate+ "," + 2*(4.92/this.pxRate)+ " " + 1.7*this.pxRate+ "," + 2*(4.92/this.pxRate)+ "")}
              ${this.writeApplianceIconBubble(2)}
              ${this.htmlWriter.writeAppliancePowerLineAndCircle(2,"M" + 1.7*this.pxRate+ "," + 4*(4.92/this.pxRate)+ " C" + 1.7*this.pxRate+ "," + 4*(4.92/this.pxRate)+ " " + 1.7*this.pxRate+ ","+17*this.pxRate+" " + 1.7*this.pxRate+ ","+17*this.pxRate)}
            </div>

**Comment by reptilex** [comment]
Thanks pman. Sorry it took a while
