### ISSUE TITLE
Feature request: 3 devices and color change

### ISSUE THREAD

**Issue by red-machine95** [reptilex/tesla-style-solar-power-card#60]
Hello and congratulations on the excellent work!

I wonder if there was a possibility to have 3 applicances instead of 2?

In my case I have an electric motorcycle and 2 electric water tanks and it was wonderful that I managed to have these 3 entities on this card. I've tried to use the battery entity, but it doesn't work as desired...

Regarding the color change, is it possible to add the functionality of changing the color to our liking instead of being limited to blue, green and orange?

**Comment by reptilex** [comment]
Colour change might be easy and be done in the near future, but I will certainly not support more than 2 appliances in the upcoming months. The problem lies in how I'm handling the animation. The way I'm doing it makes the card look mostly good but requires a recalculation of the positioning of every card item on every window change and this in pixels not percentage (svg related). Therefore adding a third appliance would require a recalculation of all the calculation I'm doing and it simply brings in too much complexity. I'm thinking of switching to a full css approach that would require a stepped velocity. Once I have that, more appliances will be easy, but the former step is going to take a while.

A crutch might be summing your water tanks and using the extra text field of that appliance to tell you a percentage of each on the consumption via a template. Might even look ok and be enough information. But I understand this is suboptimal.

**Comment by red-machine95** [comment]
I realize that adding a third device makes things difficult and there are certainly other tasks / bugs that you are facing.

Until then I will create a secondary entity of the sum of the consumption of my 2 water tanks, this way I get an idea of ​​the consumption of these 2 devices and I can add separately the consumption of my electric motorcycle.

Thanks 💪

**Comment by pman07** [comment]
You can also use the HACS add-on "card-mod" to edit colors etc. with CSS style. For example here are all the style changes I'm using. Just tack it on the end of the card config in yaml.

        style: >
          .generation_entity .acc_icon, .generation_entity { 
            color: yellow !important;
          }  .generation_entity { 
            border: 1px solid yellow !important;
          }  #generation_to_house_entity_line, #generation_to_grid_entity_line, 
          #generation_to_battery_entity_line {
              stroke: yellow !important;
          }  #generation_to_house_entity_circle,
          #generation_to_grid_entity_circle,
          #generation_to_battery_entity_circle {
              stroke: yellow !important;
              fill: yellow !important;
          } .acc_text, .acc_text_extra {
            color: white
          } .acc_container.appliance1_consumption_entity .acc_icon { 
            color: #666666 !important;
          } .acc_container.appliance1_consumption_entity { 
            border: 1px solid #666666 !important;
          } .acc_container.appliance2_consumption_entity .acc_icon { 
            color: #e82127 !important;
          } .acc_container.appliance2_consumption_entity { 
            border: 1px solid #e82127 !important;
          }
