### ISSUE TITLE
Setup with P1

### ISSUE THREAD

**Issue by tane64** [reptilex/tesla-style-solar-power-card#61]
Hi,
I have a bit different setup. Hope you can help me.

2 x Solar (shelly or I can use ephase. Last one is slow)
Grid is via P1 

P1 can be positief or negative.

Positive means there is grid usage
Negative means there is power from the solar going to the grid.

type: 'custom:tesla-style-solar-power-card'
grid_consumption_entity: sensor.p1_net_electricity_point
generation_to_house_entity: sensor.shelly_em_solar_channel_1_power_pv12
generation_to_grid_entity: sensor.shelly_em_solar_channel_2_power_pv16

Production: 1482+854 (2336)
Grid =-1792 
House =544 (2336-1792)

![pv](https://user-images.githubusercontent.com/60829997/114882306-1d167180-9e04-11eb-87ce-f54c9be648fe.jpg)

**Comment by reptilex** [comment]
Hi, you have to create templates and add/subtract/divide your values.
Let's start with grid so P1, create a template as described in the documentation to devide positive from negative.
If p1 pos is called  sensor.p1_pos and sensor.p1_neg then use 
```yml
grid_to_house: sensor.p1_pos
generation_to_grid: sensor.p1_neg
```
For your generation to house it seems to me that you need a template also, that is something like
((PV_Zolder_12 + PV Laag) - sensor.p1_neg)
But I'm not sure since PV Actueel could be the sum of that minus the losses of your inverter. Is this the case? Then you just need a template of PV Actueel - sensor.p1_neg

**Comment by tane64** [comment]
Thank you. Solved some of the problems with templates.

When I look at the the data it looks fine.

Grid should be 156W

When P1 is negative  it will also not work


type: 'custom:tesla-style-solar-power-card'
grid_to_house_entity: sensor.house_con
generation_to_grid_entity: sensor.pvproducties_shelly




<img width="512" alt="Screenshot 2021-04-16 at 18 48 53" src="https://user-images.githubusercontent.com/60829997/115057832-ccc31080-9ee4-11eb-95c1-63a8c34cff9f.png">



My template:
  - platform: template
    sensors:
      pvproducties_shelly:
       friendly_name: "Pv Productie Shelly"
       value_template:  "{{(states('sensor.shellyem_pv12')| float) + (states('sensor.shellyem_pv16') | float)}}"

      house_con:
       friendly_name: "House consumption"
       value_template: "{{( (states('sensor.pvproducties_shelly')| float) + (states('sensor.p1_net_electricity_point') | float))}}"

**Comment by reptilex** [comment]
Well you have to have three sensors:
grid_to_house: sensor.p1_pos
generation_to_grid: sensor.p1_neg
generation_to_house: ((PV_Zolder_12 + PV Laag) - sensor.p1_neg)

**Comment by tane64** [comment]
Tanks for the tips. I have collected all the correct numbers.
Can't place them at correct line to get the correct view. (at the moment only using off peak values)



<img width="500" alt="PV-House" src="https://user-images.githubusercontent.com/60829997/115147808-21899700-a05d-11eb-80f9-a42e6700240f.png">

**Comment by reptilex** [comment]
Well to me it seems, that you have to join peak and off peak into one sensor. House to grid seems to be grid feed in. But what I'm missing here is a sensor for generation to house. If you don't have that you need to create sensors template that give you the place from where your house consumption comes. Since you need at least three flows:
generation_to_grid_entity (house to grid peak + house to grid off peak)
generation_to_house_entity (maybe house consumption - (grid consumption peak + off peak))
grid_to_house_entity (grid consumption peak + grid consumption off peak)
